name: webdav

on: push

jobs:
  build:
    name: "Build and Upload Image"
    runs-on: ubuntu-latest

    steps:
      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: docker login
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u henne90gen -p $DOCKER_PASSWORD

      - name: Build Image
        run: make build-webdav

      - name: Test Image
        run: make test-webdav

      - name: Push Image
        run: make push-webdav
